name: CI

# Run this workflow whenever the build may be affected
on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'doc/**'
      - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'doc/**'
      - '**.md'

jobs:
  build-firmware:
    runs-on: ubuntu-22.04
    env:
      # InfiniTime sources are downloaded to the current directory.
      # Override SOURCES_DIR in build.sh
      SOURCES_DIR: .
    steps:
      - name: Checkout source files
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix build '.?submodules=1#infinitime'
      - name: Unzip DFU package
        run: unzip ./result/src/pinetime-mcuboot-app-dfu-*.zip -d ./pinetime-mcuboot-app-dfu
      - name: Upload DFU artifacts
        uses: actions/upload-artifact@v3
        with:
          name: InfiniTime DFU ${{ github.head_ref }}
          path: ./pinetime-mcuboot-app-dfu/
      - name: Upload MCUBoot image artifacts
        uses: actions/upload-artifact@v3
        with:
          name: InfiniTime MCUBoot image ${{ github.head_ref }}
          path: ./result/src/pinetime-mcuboot-app-image-*.bin
      - name: Upload standalone ELF artifacts
        uses: actions/upload-artifact@v3
        with:
          name: InfiniTime image ${{ github.head_ref }}
          path: ./result/src/pinetime-app-*.out
      - name: Upload resources artifacts
        uses: actions/upload-artifact@v3
        with:
          name: InfiniTime resources ${{ github.head_ref }}
          path: ./result/src/infinitime-resources-*.zip
