name: CI

# Run this workflow whenever the build may be affected
on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'doc/**'
      - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'doc/**'
      - '**.md'

jobs:
  build-firmware:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout source files
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix build '.?submodules=1#infinitime'
      - name: Unzip DFU package
        run: unzip ./result/src/pinetime-mcuboot-app-dfu-*.zip -d ./pinetime-mcuboot-app-dfu
      - name: Upload DFU files
        uses: actions/upload-artifact@v4
        with:
          name: pinetime-mcuboot-app-dfu
          path: ./pinetime-mcuboot-app-dfu/
      - name: Upload MCUBoot image
        uses: actions/upload-artifact@v4
        with:
          name: pinetime-mcuboot-app-image.bin
          path: ./result/src/pinetime-mcuboot-app-image-*.bin
      - name: Upload standalone ELF files
        uses: actions/upload-artifact@v4
        with:
          name: pinetime-app.out
          path: ./result/src/pinetime-app-*.out
      - name: Upload resources
        uses: actions/upload-artifact@v4
        with:
          name: infinitime-resources.zip
          path: ./result/src/resources/infinitime-resources-*.zip
